website/local_tester/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'

  resources :contests, except: [:show] do
    resources :problems, controller: 'contest/problems', only: [:index, :show] do
      resources :submissions, controller: 'contest/submissions', only: [:new, :create]
    end
    resources :submissions, controller: 'contest/submissions', only: [:index, :show] do
      member do
        post 'rejudge'
      end
    end
  end

  resources :problems do
    member do
      post 'resync'
    end
  end

  resources :submissions, only: [:index, :show, :destroy]

end

website/local_tester/app/models/problem.rb
class Problem < ActiveRecord::Base
  mount_uploader :data, DataUploader

  has_one :solution, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_and_belongs_to_many :contests

  before_save :render_body

  def sync_data
    require 'socket'
    require 'yaml'

    begin
      client = TCPSocket.new BACKGROUND_HOST, BACKGROUND_PORT
    rescue
      client = nil
    end

    if client
      client.send "put #{self.data.file.filename}", 0
      if client.recvfrom(4096)[0] == 'ready'
        File.open(self.data.path, 'rb') do |f|
          while data = f.read(4096)
            client.send data, 0
          end
        end
        client.send 'EOF', 0

        if client.recvfrom(4096)[0] == 'ready'
          client.send 'put request.yaml', 0
          if client.recvfrom(4096)[0] == 'ready'
            request = YAML::dump({
              'Order' => ['install_problem'],
              'Name' => [self.id],
              'Package' => [self.data.file.filename]
            })
            client.send request, 0
            client.send 'EOF', 0

            if client.recvfrom(4096)[0] == 'ready'
              self.data_synced = true
              self.save
              return true
            end
          end
        end
      end
    end
    false
  end

  private

  def render_body
    require 'redcarpet'
    renderer = Redcarpet::Render::HTML.new
    extensions = { fenced_code_blocks: true }
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)

    self.rendered_sample_input = redcarpet.render "~~~\n#{self.sample_input}\n~~~"
    self.rendered_sample_output = redcarpet.render "~~~\n#{self.sample_output}\n~~~"
  end
end

website/local_tester/app/controllers/contest/problems_controller.rb
class Contest::ProblemsController < ApplicationController
  def index
    @contest = Contest.find(params[:contest_id])
    @problems = @contest.problems
  end

  def show
    @contest = Contest.find(params[:contest_id])
    @problem = @contest.problems.find(params[:id])
  end
end

website/local_tester/app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def index
    @problems = Problem.order(id: :desc)
  end

  def show
    @problem = Problem.find(params[:id])
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = Problem.new(permit_params)
    if @problem.save
      flash[:notice] = 'Successfully created problem.'
      redirect_to problem_path(@problem)
    else
      render action: :new
    end
  end

  def edit
    @problem = Problem.find(params[:id])
  end

  def update
    @problem = Problem.find(params[:id])
    if @problem.update(permit_params)
      flash[:notice] = 'Successfully updated problem. Data is being synchronized in background.'
      if params[:problem][:data]
        @problem.data_synced = false
        @problem.save
        @problem.delay.sync_data if params[:problem][:data]
      end
      redirect_to problem_path(@problem)
    else
      render action: :edit
    end
  end

  def resync
    @problem = Problem.find(params[:id])
    if @problem.data?
      flash[:notice] = 'Successfully start to resynchronize data in background.'
      @problem.data_synced = false
      @problem.save
      @problem.delay.sync_data
    end
    redirect_to problems_path
  end

  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy
    flash[:notice] = 'Successfully deleted problem'
    redirect_to problems_path
  end

  private

  def permit_params
    params[:problem].permit(:name, :description, :input_format, :output_format, :sample_input, :sample_output, :hint, :data, :time_limit, :memory_limit, :case_num, :case_score)
  end
end

website/local_tester/app/helpers/problems_helper.rb
module ProblemsHelper
end

website/local_tester/app/views/problems/_disp.html.haml
%table.table.table-hover
  %tr
    %th Time limit
    %td= "#{@problem.time_limit} ms"
  %tr
    %th Memory limit
    %td= "#{@problem.memory_limit} mb"
  %tr
    %th Case num
    %td= "#{@problem.case_num}"
  %tr
    %th Case score
    %td= "#{@problem.case_score}"
- [:description, :input_format, :output_format, :rendered_sample_input, :rendered_sample_output, :hint].each do |sym|
  .panel.panel-default
    .panel-heading
      %h3.panel-title= sym.to_s.humanize
    .panel-body
      - if sym.to_s =~ /sample/
        ~ @problem.send(sym).html_safe
      - else
        = @problem.send(sym).html_safe

website/local_tester/app/views/problems/edit.html.haml
%h2.page-header Edit problem
= simple_form_for @problem do |f|
  = f.input :name, required: true, input_html: { class: 'form-control' }
  = f.input :time_limit, as: :integer, input_html: { class: 'form-control' }
  = f.input :memory_limit, as: :integer, input_html: { class: 'form-control' }
  = f.input :description, as: :ckeditor
  = f.input :input_format, as: :ckeditor
  = f.input :output_format, as: :ckeditor
  = f.input :sample_input, input_html: { class: 'form-control' }
  = f.input :sample_output, input_html: { class: 'form-control' }
  = f.input :hint, as: :ckeditor
  %hr
  %h3 Data
  - if @problem.data?
    %p
      = @problem.data.file.filename
      = link_to 'Download', @problem.data_url
  = f.input :data, label: false, as: :file, input_html: { class: 'form-control' }
  = f.input :case_num, as: :integer, input_html: { class: 'form-control' }
  = f.input :case_score, as: :integer, input_html: { class: 'form-control' }
  %br
  = f.submit class: 'btn btn-primary'
  = link_to 'Cancel', :back, class: 'btn btn-default'

website/local_tester/app/views/problems/index.html.haml
%h1.page-header
  Problems
  = link_to 'New problem', new_problem_path, class: 'btn btn-success pull-right'
%table.table.table-hover
  %thead
    %tr
      %th Id
      %th Name
      %th Created at
      %th Data synced?
      %th &nbsp;
  %tbody
    - @problems.each do |problem|
      %tr
        %td= link_to problem.id, problem_path(problem)
        %td= link_to problem.name, problem_path(problem)
        %td= problem.created_at
        %td
          = problem.data_synced?
          = link_to 'Resync', resync_problem_path(problem), method: :post
        %td
          = link_to 'View', problem_path(problem)
          = link_to 'Edit', edit_problem_path(problem)
          = link_to 'Delete', problem_path(problem), method: :delete, data: { confirm: 'Are you sure you want to delete this problem?' }

website/local_tester/app/views/problems/new.html.haml
%h2.page-header New problem
= simple_form_for @problem do |f|
  = f.input :name, required: true, input_html: { class: 'form-control' }
  = f.input :time_limit, as: :integer, input_html: { class: 'form-control' }
  = f.input :memory_limit, as: :integer, input_html: { class: 'form-control' }
  = f.input :description, as: :ckeditor
  = f.input :input_format, as: :ckeditor
  = f.input :output_format, as: :ckeditor
  = f.input :sample_input, input_html: { class: 'form-control' }
  = f.input :sample_output, input_html: { class: 'form-control' }
  = f.input :hint, as: :ckeditor
  %br
  = f.submit class: 'btn btn-primary'
  = link_to 'Cancel', :back, class: 'btn btn-default'

website/local_tester/app/views/problems/show.html.haml
%h2.page-header
  = @problem.name
  = link_to 'Edit this problem', edit_problem_path(@problem), class: 'btn btn-info pull-right'
= render 'disp'