website/local_tester/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'

  resources :contests, except: [:show] do
    resources :problems, controller: 'contest/problems', only: [:index, :show] do
      resources :submissions, controller: 'contest/submissions', only: [:new, :create]
    end
    resources :submissions, controller: 'contest/submissions', only: [:index, :show] do
      member do
        post 'rejudge'
      end
    end
  end

  resources :problems do
    member do
      post 'resync'
    end
  end

  resources :submissions, only: [:index, :show, :destroy]

end

website/local_tester/app/models/contest.rb
class Contest < ActiveRecord::Base
  has_and_belongs_to_many :problems
  has_many :submissions, dependent: :destroy
end

website/local_tester/app/controllers/contest/problems_controller.rb
class Contest::ProblemsController < ApplicationController
  def index
    @contest = Contest.find(params[:contest_id])
    @problems = @contest.problems
  end

  def show
    @contest = Contest.find(params[:contest_id])
    @problem = @contest.problems.find(params[:id])
  end
end

website/local_tester/app/controllers/contest/submissions_controller.rb
class Contest::SubmissionsController < ApplicationController
  def index
    @contest = Contest.find(params[:contest_id])
    lim = {}
    lim[:problem_id] = params[:problem_id] if params[:problem_id]
    @submissions = @contest.submissions.where(lim).order(id: :desc)
  end

  def show
    @contest = Contest.find(params[:contest_id])
    @submission = @contest.submissions.find(params[:id])
  end

  def new
    @contest = Contest.find(params[:contest_id])
    @problem = @contest.problems.find(params[:problem_id])
    @submission = @problem.submissions.build(contest: @contest)
  end

  def create
    @contest = Contest.find(params[:contest_id])
    @problem = @contest.problems.find(params[:problem_id])
    @submission = @problem.submissions.new(permit_params)
    @submission.time_cost = -1
    @submission.memory_cost = -1
    @submission.result = 'Pending'
    if @submission.save
      flash[:notice] = 'Successfully created submission.'
      @submission.delay.judge
      redirect_to contest_submissions_path(@contest)
    else
      render action: :new
    end
  end

  def rejudge
    @contest = Contest.find(params[:contest_id])
    @submission = @contest.submissions.find(params[:id])
    if ['Pending', 'Waiting', 'Running'].include? @submission.result
      flash[:alert] = 'The submission is being judged.'
    else
      flash[:notice] = 'Successfully rejudged submission.'
      @submission.result = 'Pending'
      @submission.save
      @submission.delay.judge
    end
    redirect_to contest_submissions_path(@contest)
  end

  private

  def permit_params
    params[:submission].permit(:contest_id, :language, :code)
  end
end

website/local_tester/app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def index
    @contests = Contest.order(id: :desc)
  end

  def new
    @contest = Contest.new
  end

  def create
    @contest = Contest.new(permit_params)
    if @contest.save
      flash[:notice] = 'Successfully created contest.'
      redirect_to contest_problems_path(@contest)
    else
      render action: :new
    end
  end

  def edit
    @contest = Contest.find(params[:id])
    @problems = @contest.problems
  end

  def update
    @contest = Contest.find(params[:id])
    if @contest.update(permit_params)
      problems = []
      params.keys.grep(/^problem_id_/).each do |problem_id_form_token|
        problem_id = params[problem_id_form_token]
        Problem.where(id: problem_id).each do |problem|
          problems << problem
        end
      end
      @contest.problems = []
      @contest.problems = problems.uniq
      flash[:notice] = 'Successfully updated contest.'
      redirect_to contest_problems_path(@contest)
    else
      render action: :edit
    end
  end

  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy
    flash[:notice] = 'Successfully deleted contest.'
    redirect_to contests_path
  end

  private

  def permit_params
    params[:contest].permit(:name)
  end
end

website/local_tester/app/helpers/contests_helper.rb
module ContestsHelper
  def contest_submissions_path_with_hash(contest, hash)
    hash[:id] = contest.id
    contest_submissions_path(hash)
  end

  def count_contest_submissions_with_hash(contest, hash)
    contest.submissions.where(hash).size
  end
end

website/local_tester/app/views/contests/edit.html.haml
%h2.page-header Edit contest
= simple_form_for @contest do |f|
  = f.input :name, required: true, input_html: { class: 'form-control' }
  %hr
  %h3
    Problems
    = link_to 'Add problem', '#problems', class: 'btn btn-success', onclick: 'add_problem()'
    #problems 
      - @problems.each do |problem|
        .form-inline{:id => "problem_#{problem.hash}"}
          %br
          %input{:id => "problem_id_#{problem.hash}", :name => "problem_id_#{problem.hash}", :type => 'text', :placeholder => 'Problem id', :class => 'form-control', :value => problem.id}
          %a{:id => "rm_problem_#{problem.hash}", :onclick => "rm_problem(\"#{problem.hash}\")", :class => 'btn btn-danger'} Delete
          %br
  %br
  = f.submit class: 'btn btn-primary'
  = link_to 'Cancel', :back, class: 'btn btn-default'
:javascript
  var cnt = 0;
  function add_problem() {
    $("#problems").append("<div class='form-inline' id='problem_" + cnt + "'></div>");
    $("#problem_" + cnt).append("<br /><input id='problem_id_" + cnt + "' name='problem_id_" + cnt + "' type='text' placeholder='Problem id' class='form-control' />");
    $("#problem_" + cnt).append(" <a id='rm_problem_" + cnt + "' onclick='rm_problem(" + cnt + ")' class='btn btn-danger'>Delete</a><br />");
    cnt = cnt + 1;
  }
  function rm_problem(id) {
    $("#problem_" + id).remove();
  }

website/local_tester/app/views/contests/index.html.haml
%h1.page-header
  Contests
  = link_to 'New contest', new_contest_path, class: 'btn btn-success pull-right'
%table.table.table-hover
  %thead
    %tr
      %th Id
      %th Name
      %th Created at
      %th &nbsp;
  %tbody
    - @contests.each do |contest|
      %tr
        %td= link_to contest.id, contest_problems_path(contest)
        %td= link_to contest.name, contest_problems_path(contest)
        %td= contest.created_at
        %td
          = link_to 'View', contest_problems_path(contest)
          = link_to 'Edit', edit_contest_path(contest)
          = link_to 'Delete', contest_path(contest), method: :delete, data: { confirm: 'Are you sure you want to delete this contest?' }

website/local_tester/app/views/contests/new.html.haml
%h2.page-header New contest
= simple_form_for @contest do |f|
  = f.input :name, required: true, input_html: { class: 'form-control' }
  %br
  = f.submit class: 'btn btn-primary'
  = link_to 'Cancel', :back, class: 'btn btn-default'