website/local_tester/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'

  resources :contests, except: [:show] do
    resources :problems, controller: 'contest/problems', only: [:index, :show] do
      resources :submissions, controller: 'contest/submissions', only: [:new, :create]
    end
    resources :submissions, controller: 'contest/submissions', only: [:index, :show] do
      member do
        post 'rejudge'
      end
    end
  end

  resources :problems do
    member do
      post 'resync'
    end
  end

  resources :submissions, only: [:index, :show, :destroy]

end

website/local_tester/app/models/contest.rb
class Contest < ActiveRecord::Base
  has_and_belongs_to_many :problems
  has_many :submissions, dependent: :destroy
end

website/local_tester/app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :problem
  belongs_to :contest

  before_save :render_code

  def loaded_result
    require 'yaml'
    YAML::load(self.details || YAML::dump({}))
  end

  def judge
    require 'socket'
    require 'yaml'

    self.result = 'Waiting'
    self.save

    begin
      client = TCPSocket.new BACKGROUND_HOST, BACKGROUND_PORT
    rescue
      client = nil
    end

    if client
      self.result = 'Running'
      self.save

      client.send 'put request.yaml', 0
      if client.recvfrom(4096)[0] == 'ready'
        request = YAML::dump({
          'Order' => ['test'],
          'ProblemName' =>  [self.problem.id],
          'Name' => ['default'],
          'Language' => [self.language],
          'TimeLimit' => [self.problem.time_limit],
          'MemoryLimit' => [self.problem.memory_limit],
          'OutputLimit' => [BACKGROUND_OUTPUT_LIMIT],
          'CaseNum' => [self.problem.case_num],
          'ScoreForEachCase' => [self.problem.case_score],
          'CheckMode' => ['line'],
          'Code' => [self.code]
        })
        client.send request, 0
        client.send 'EOF', 0
        client.recvfrom(4096)[0]

        if client.recvfrom(4096)[0] == 'ready'
          client.send 'get result.yaml', 0
          if client.recvfrom(4096)[0] == 'ready'
            judge_result = client.recvfrom(131072)[0]
            self.result = 'Judged'
            self.details = judge_result

            judge_result = YAML::load(judge_result)
            self.time_cost = 0
            self.memory_cost = 0
            judge_result.keys.grep(/^Case/).each do |kase|
              self.time_cost += judge_result[kase]['Time'][0].to_i
              self.memory_cost = [self.memory_cost, judge_result[kase]['Memory'][0].to_i].max
            end
          end
        end

        client.close
      else
        self.result = 'Judge_Error'
      end
    else
      self.result = 'Judge_Error'
    end

    self.save
  end

  private

  def render_code
    require 'redcarpet'
    renderer = PygmentizeHTML.new
    extensions = { fenced_code_blocks: true }
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)

    self.rendered_code = redcarpet.render "~~~ #{self.language}\n#{self.code}\n~~~"
  end
end

class PygmentizeHTML < Redcarpet::Render::HTML
  def block_code(code, language)
    require 'pygmentize'
    Pygmentize.process(code, language)
  end
end

website/local_tester/app/controllers/contest/problems_controller.rb
class Contest::ProblemsController < ApplicationController
  def index
    @contest = Contest.find(params[:contest_id])
    @problems = @contest.problems
  end

  def show
    @contest = Contest.find(params[:contest_id])
    @problem = @contest.problems.find(params[:id])
  end
end

website/local_tester/app/controllers/contest/submissions_controller.rb
class Contest::SubmissionsController < ApplicationController
  def index
    @contest = Contest.find(params[:contest_id])
    lim = {}
    lim[:problem_id] = params[:problem_id] if params[:problem_id]
    @submissions = @contest.submissions.where(lim).order(id: :desc)
  end

  def show
    @contest = Contest.find(params[:contest_id])
    @submission = @contest.submissions.find(params[:id])
  end

  def new
    @contest = Contest.find(params[:contest_id])
    @problem = @contest.problems.find(params[:problem_id])
    @submission = @problem.submissions.build(contest: @contest)
  end

  def create
    @contest = Contest.find(params[:contest_id])
    @problem = @contest.problems.find(params[:problem_id])
    @submission = @problem.submissions.new(permit_params)
    @submission.time_cost = -1
    @submission.memory_cost = -1
    @submission.result = 'Pending'
    if @submission.save
      flash[:notice] = 'Successfully created submission.'
      @submission.delay.judge
      redirect_to contest_submissions_path(@contest)
    else
      render action: :new
    end
  end

  def rejudge
    @contest = Contest.find(params[:contest_id])
    @submission = @contest.submissions.find(params[:id])
    if ['Pending', 'Waiting', 'Running'].include? @submission.result
      flash[:alert] = 'The submission is being judged.'
    else
      flash[:notice] = 'Successfully rejudged submission.'
      @submission.result = 'Pending'
      @submission.save
      @submission.delay.judge
    end
    redirect_to contest_submissions_path(@contest)
  end

  private

  def permit_params
    params[:submission].permit(:contest_id, :language, :code)
  end
end

website/local_tester/app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def index
    @contests = Contest.order(id: :desc)
  end

  def new
    @contest = Contest.new
  end

  def create
    @contest = Contest.new(permit_params)
    if @contest.save
      flash[:notice] = 'Successfully created contest.'
      redirect_to contest_problems_path(@contest)
    else
      render action: :new
    end
  end

  def edit
    @contest = Contest.find(params[:id])
    @problems = @contest.problems
  end

  def update
    @contest = Contest.find(params[:id])
    if @contest.update(permit_params)
      problems = []
      params.keys.grep(/^problem_id_/).each do |problem_id_form_token|
        problem_id = params[problem_id_form_token]
        Problem.where(id: problem_id).each do |problem|
          problems << problem
        end
      end
      @contest.problems = []
      @contest.problems = problems.uniq
      flash[:notice] = 'Successfully updated contest.'
      redirect_to contest_problems_path(@contest)
    else
      render action: :edit
    end
  end

  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy
    flash[:notice] = 'Successfully deleted contest.'
    redirect_to contests_path
  end

  private

  def permit_params
    params[:contest].permit(:name)
  end
end

website/local_tester/app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def index
    @submissions = Submission.order(id: :desc)
  end

  def show
    @submission = Submission.find(params[:id])
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    flash[:notice] = 'Successfully deleted submission.'
    redirect_to submissions_path
  end
end

website/local_tester/app/helpers/contests_helper.rb
module ContestsHelper
  def contest_submissions_path_with_hash(contest, hash)
    hash[:id] = contest.id
    contest_submissions_path(hash)
  end

  def count_contest_submissions_with_hash(contest, hash)
    contest.submissions.where(hash).size
  end
end

website/local_tester/app/helpers/submissions_helper.rb
module SubmissionsHelper
end

website/local_tester/app/views/contest/submissions/index.html.haml
= render 'contest/layout'
%table.table.table-hover
  %thead
    %tr
      %th Id
      %th Created at
      %th Problem
      %th Result
      %th Total score
      %th Time
      %th Memory
      %th Language
      %th Code Length
      %th &nbsp;
  %tbody
    - @submissions.each do |submission|
      - result = submission.loaded_result
      %tr
        %td= link_to submission.id, contest_submission_path(@contest, submission)
        %td= submission.created_at
        %td= link_to submission.problem.id, contest_problem_path(@contest, submission.problem)
        %td= submission.result
        %td= link_to result['totalScore'] || 0, contest_submission_path(@contest, submission)
        %td= "#{submission.time_cost} ms"
        %td= "#{submission.memory_cost} kb"
        %td= link_to submission.language, contest_submission_path(@contest, submission)
        %td= "#{submission.code.size} B"
        %td= link_to 'Rejudge', rejudge_contest_submission_path(@contest, submission), method: :post

website/local_tester/app/views/contest/submissions/new.html.haml
= render 'contest/layout'
%h3.page-header 
  New submission
  %small= "Problem ##{@problem.id} - #{@problem.name}"
  = link_to 'Back to the problem', contest_problem_path(@contest, @problem), class: 'btn btn-default pull-right'
= simple_form_for [@contest, @problem, @submission] do |f|
  = f.hidden_field :contest_id
  = f.label :language, required: true
  = f.select :language, options_for_select([['C++', 'cpp'], ['C', 'c'], ['Pascal', 'pascal']], 'cpp'), {}, { class: 'form-control' }
  = f.input :code, input_html: { class: 'form-control', rows: '8' }
  %br
  = f.submit class: 'btn btn-primary'
  = link_to 'Cancel', :back, class: 'btn btn-default'

website/local_tester/app/views/contest/submissions/show.html.haml
= render 'contest/layout'
%h3.page-header
  Submission
  = "##{@submission.id}"
  = link_to 'Back', :back, class: 'btn btn-sm btn-default pull-right'
= render 'submissions/disp'